### ISSUE TITLE
Alexa Home stopped working

### ISSUE THREAD

**Issue by tvan0076** [hardillb/node-red-alexa-home-skill-web#105]
All, I have been using the service for about 3 months, and it has been awesome!  I had to reconfigure some settings and it stopped working.  So, Here is what I have tried:
removed the Alexa Skill
removed the scenes in smart home
deleted all nodes
deleted node red configuration node with account information

Started from scratch with a new username and password on hardillb and set everything back up.  Now I just get "Ok" from Alexa and nothing triggers.  Everything shows connected but nothing works :-(  Any ideas??

**Comment by hardillb** [comment]
I'm going to need a lot more information before I can start to help.

 - What are both the old and new username on the site?
 - Do you get a consistent green connected dot under the alexa-in node?
 - What happens if you connect a debug node to the alexa-in node?
 - Are you using the alexa-response node?
 - Did you remember to ask "alexa, discover devices" after you removed and re-added everything?

As a test start simple:

 1. remove all devices from the service
 2. remove all the device nodes from Node-RED (you can leave the config node)
 3. ask "alexa, discover devices (to clear out any old devices)
 4. add a single simple device (e.g. a light with just on/off) on the website
 5. add an alexa-in node and click the refresh button before selecting the new test device
 6. attach a debug node to the test device node
 7. deploy changes to flow
 8. wait for constant connected green dot
 9. ask "alexa, discover devices"
 10. ask "alexa, turn on test device"

Do you get any output in the debug node?

**Comment by tvan0076** [comment]
All, I think I have it figure out.  Before changing my settings I could
just tell Alexa an activity "Alexa, Wake up" and she did it. Now looks like
I have to also tell her to turn on an activity "Alexa, turn on wake up".
Not sure what has changed, but this is working.  I wish that wasn't the
case, but for now, I have a way forward.

**Comment by hardillb** [comment]
OK, so it sounds like all my stuff is working. I'll close this issue for now.
