### ISSUE TITLE
Differentiate which Echo issued the command

### ISSUE THREAD

**Issue by nxarmada** [hardillb/node-red-alexa-home-skill-web#153]
it would be cool if there was a way to Differentiate which Echo issued the command in node red.  I have an Echo in every room of the house and I want to set it up when you issue the command say "Alex, Turn Lights Off" it only does it to the room where the Echo that received the command is in.

**Comment by hardillb** [comment]
This is not possible with the Alexa API that backs the service

**Comment by Bra1nK** [comment]
Alexa already does this for you if you set up rooms and device types properly, you only need node-red to do the switching of the named devices. For example my bedroom has a tuya bulb (named 'bedroom light') and a node-red controlled relay (named 'Lamp') which switches a bedside lamp. Both are device type 'Light'. I can switch them individually by name but switch them both by saying "Alexa turn the light on" whilst close to the bedroom Echo Show because I've set them all in the same 'Room' in the Alexa app. Hope this helps.
