### ISSUE TITLE
Skill approval, and/or beta test?

### ISSUE THREAD

**Issue by terafin** [hardillb/node-red-alexa-home-skill-web#3]
Hi there! Would love to try out your alexa skill but It appears to still not be out on the store. Am I missing something obvious? 

(I did also create an account here: https://alexa-node-red.bm.hardill.me.uk/)

Thanks!

**Comment by hardillb** [comment]
It's still with Amazon for approval and unfortunately the only way to add Beta users is to allow full developer access to the Amazon Developer account that hosts the skill which I'm only prepared to do for people I know.

I'm sorry you will just have to be a little more patient while Amazon get round to approving it. The problem is if they find anything wrong with a submission it takes over 3 weeks before they get round to looking again and there doesn't seam to be a well documented list of what needs to be done how to get approved.

**Comment by terafin** [comment]
Thanks so much for responding! No worries, glad to see I wasn't missing something obvious. Best of luck with Amazon!

**Comment by hardillb** [comment]
The skill has gone live now if you want to have a play
