### ISSUE TITLE
Disconnected node

### ISSUE THREAD

**Issue by jammin9** [hardillb/node-red-alexa-home-skill-web#42]
Followed all procedures.  Unable to get Node to connect.  Is this because I am in Canada? I was abe to download the Node-red skill on the Alexa app.  

I noticed this in the documentation but it is not clear.

1.Amazon documentation say only available to US users at the moment
2.Amazon documentation say only available to US & UK users at the moment
3.Can not be Auto Acknowledged as they need to return a value

**Comment by peakmonitor** [comment]
Same for me, in USA

**Comment by hardillb** [comment]
No, the node should connect from anywhere, Amazon limits certain command to some specific regions, Which is what the section of the documentation you mention is talking about, those items refer to the list of commands just above, with the numbers referring to the super scripts against the actions.

![selection_019](https://user-images.githubusercontent.com/1800845/35181234-ea541154-fdb5-11e7-85cb-aa092ae90f40.png)

I'm going to need a lot more information to work out what's the problem is, as a starting point I need the following.

 1. What is your username on the alexa-node-red website?
 2. Is the node cycling between connected/disconnected or does it just stay disconnected?
 3. Is there any output in the node-red logs regarding the node?

It might be easier to try and trouble shoot this live so you can also log into the Node-RED Slack team and join the #alexa channel and if I'm around we can try and work it out.

**Comment by hardillb** [comment]
Also when did you create your accounts on the system?

**Comment by peakmonitor** [comment]
Ah, I figured my issue out:  I had an older version of node.js.  I updated everything using update-nodejs-and-nodered and now it works. Current versions running is v8.9.4
This skill is really useful, thanks for creating it!

**Comment by jammin9** [comment]
NVM I figured it out. It was just the capital J in my username.

My bad, thank you for your responses!
